<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Borrowing\LibraryApp.Borrowing.Contracts\LibraryApp.Borrowing.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\Borrowing\LibraryApp.Borrowing.Infrastructure\LibraryApp.Borrowing.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Catalog\LibraryApp.Catalog.Contracts\LibraryApp.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\Catalog\LibraryApp.Catalog.Infrastructure\LibraryApp.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Members\LibraryApp.Members.Contracts\LibraryApp.Members.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\Members\LibraryApp.Members.Infrastructure\LibraryApp.Members.Infrastructure.csproj" />
  </ItemGroup>

</Project>
